---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Create a Docker group
      group: name=docker state=present
    - name: Add the vagrant user to Docker group
      user: name=vagrant groups=docker append=yes
    - name: Install Docker
      apt: name=docker.io state=present
    - name: Enable and Start Docker Daemon
      service: name=docker state=started enabled=yes
    
      
    - name: Install Forever (to run our Node.js app).
      npm: name=forever global=yes state=present
    
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - virtualenv
        state: latest
        update_cache: true

    - name: Clone a github repository
      git:
        repo: https://github.com/zaktales/yolo.git
        dest: /home/vagrant/yolo
        clone: yes
        update: yes

    - name: run docker-compose
      become_user: vagrant
      docker_compose:
        project_src: /home/vagrant/yolo
        state: present