---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create a Docker group
      group: name=docker state=present
    - name: Add the vagrant user to Docker group
      user: name=vagrant groups=docker append=yes
    - name: Install Docker
      apt: name=docker.io state=present
    - name: Enable and Start Docker Daemon
      service: name=docker state=started enabled=yes
    - name: add apt key for nodesource
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    - name: install nodejs
      apt: name=nodejs
    - name: install npm
      apt: name=npm
      